language: swift
os: osx
osx_image: xcode10.1

notifications:
  email: false

env:
  global:
    - DB_USER=root
    - DB_PASS=
    - DB_NAME=timetest

before_install:
  - brew install mysql@5.7
  - brew tap homebrew/services
  - brew services start mysql@5.7
  - brew link mysql@5.7 --force
  - git clone --depth 1 git://github.com/Tornquist/Time-API.git
  - (cd Time-API && npm install)
  - (cd Time-API && scripts/setup-travis.sh)

script:
  - |
    set -o pipefail && xcodebuild test \
      -workspace Time.xcworkspace \
      -scheme Shared-Tests \
      -sdk macosx10.14 \
      CODE_SIGN_IDENTITY="" \
      CODE_SIGNING_REQUIRED=NO \
      | xcpretty
