language: swift
os: osx
osx_image: xcode10.2

notifications:
  email: false

matrix:
  include:
    - env:
      - SCHEME=Shared-Tests-macOS
      - DESTINATION="platform=macOS,arch=x86_64"
    - env:
      - SCHEME=Shared-Tests-iOS
      - DESTINATION="platform=iOS Simulator,name=iPhone X,OS=12.1"

env:
  global:
    - DB_USER=root
    - DB_PASS=
    - DB_NAME=timetest

cache:
  directories:
    - Time-API/node_modules

before_install:
  - brew install mysql@5.7
  - brew tap homebrew/services
  - brew services start mysql@5.7
  - brew link mysql@5.7 --force

install:
  # Clone API and merge current source with cached node_modules.
  - git clone --depth 1 --single-branch --branch timezones git://github.com/Tornquist/Time-API.git api
  - cp -a api/. Time-API/
  - rm -rf api
  # Install API dependencies. Create and migrate database.
  - (cd Time-API && npm install)
  - (cd Time-API && scripts/setup-travis.sh)
  - (cd Time-API && npm start &) && sleep 2

script:
  - |
    set -o pipefail &&
      xcodebuild test \
        -workspace Time.xcworkspace \
        -scheme "$SCHEME" \
        -destination "$DESTINATION" \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
